**1. Evaluate coscos and sinsin on the interval [0,1][0,1] and then stack the results into a tall array with rows being the (cos(x),sin(x))(cos⁡f()(x),sinf()⁡(x)) entries.**

In [1]:
import numpy as np

In [38]:
arr = (np.linspace(0,1))

# cos and sin
arr_cos = np.cos(arr)
arr_sin = np.sin(arr)

# derivative of cos and sin
diff_cos = np.diff(arr_cos)
diff_sin = np.diff(arr_sin)

In [39]:
np.concatenate((arr_cos, arr_sin, diff_cos, diff_sin), axis=0)

array([ 1.00000000e+00,  9.99791761e-01,  9.99167129e-01,  9.98126366e-01,
        9.96669905e-01,  9.94798352e-01,  9.92512486e-01,  9.89813260e-01,
        9.86701799e-01,  9.83179396e-01,  9.79247521e-01,  9.74907810e-01,
        9.70162071e-01,  9.65012279e-01,  9.59460581e-01,  9.53509288e-01,
        9.47160879e-01,  9.40417997e-01,  9.33283451e-01,  9.25760213e-01,
        9.17851415e-01,  9.09560352e-01,  9.00890476e-01,  8.91845398e-01,
        8.82428886e-01,  8.72644861e-01,  8.62497399e-01,  8.51990724e-01,
        8.41129213e-01,  8.29917390e-01,  8.18359925e-01,  8.06461629e-01,
        7.94227460e-01,  7.81662512e-01,  7.68772018e-01,  7.55561347e-01,
        7.42036000e-01,  7.28201612e-01,  7.14063943e-01,  6.99628882e-01,
        6.84902440e-01,  6.69890751e-01,  6.54600067e-01,  6.39036755e-01,
        6.23207299e-01,  6.07118290e-01,  5.90776429e-01,  5.74188523e-01,
        5.57361479e-01,  5.40302306e-01,  0.00000000e+00,  2.04067467e-02,
        4.08049943e-02,  

**2. Create a random 3×53×5 array using the np.random.rand(3, 5) function and compute: the sum of all the entries, the sum of the rows and the sum of the columns. (Just like sorted had an optional key= argument, many Numpy functions have an optional axis= argument!)**

In [8]:
# Create 3X5 random array
rand1 = np.random.rand(3,5)

# Calculate sum of rows and put it in an array
rowsum1 = rand1.sum(axis=1)

# Calculate sum of columns and put it in an array
colsum1 = rand1.sum(axis=0)

# Original array
print('The original 3X5 random array is: ')
print(rand1)

The original random array is: 
[[0.73686975 0.81601335 0.3625006  0.74074204 0.65532673]
 [0.89316736 0.19368954 0.2310693  0.79021479 0.19308573]
 [0.84557715 0.77196409 0.6990438  0.80402481 0.94895082]]


In [9]:
# Sum of rows
print('Sum of the 3 rows: ')
print(rowsum1)

The original random array is: 
[3.31145246 2.30122673 4.06956066]


In [10]:
# Sum of columns
print('Sum of the 5 columns: ')
print(colsum1)

Sum of the 5 columns: 
[2.47561426 1.78166698 1.29261369 2.33498164 1.79736328]


**3. Create a random 5×55×5 array using the function np.random.rand(5, 5). We want to sort the rows according to the second column. Try combining array slicing + argsort + indexing to do this.**

In [16]:
# Create 3X5 random array
rand2 = np.random.rand(5,5)

print('The original random array is:')
print(rand2)

The original random array is:
[[0.72647076 0.18410716 0.25592108 0.76218859 0.90856839]
 [0.22575417 0.28510321 0.26640663 0.00465807 0.13115311]
 [0.30392757 0.62789906 0.91427095 0.26483916 0.06785717]
 [0.34876133 0.31036651 0.84287758 0.08003421 0.94992997]
 [0.27132038 0.88971208 0.58637259 0.52149879 0.83080709]]


In [18]:
# argsort will return an array of indices based on the second column
# The array will then be sorted based on those indices
rand2_sort = rand2[np.argsort(rand2[:, 1])]

print('The random array sorted by the second column:')
print(rand2_sort)

The random array sorted by the second column:
[[0.72647076 0.18410716 0.25592108 0.76218859 0.90856839]
 [0.22575417 0.28510321 0.26640663 0.00465807 0.13115311]
 [0.34876133 0.31036651 0.84287758 0.08003421 0.94992997]
 [0.30392757 0.62789906 0.91427095 0.26483916 0.06785717]
 [0.27132038 0.88971208 0.58637259 0.52149879 0.83080709]]
